### ISSUE TITLE
[Normal] Migrations 

### ISSUE THREAD

**Issue by Nemtecl** [Open-Street-Art/osa-back#40]
Il serait interessant de voir l'utilisation de migrations de BD (notamment avec Flyway ou Liquibase).

Le seed initial pourrait se faire via les migrations.

Je peux vous montrer un exemple lors d'une réunion

**Comment by arnaudperalta** [comment]
Nous avons choisi d'utiliser Flyway pour la migration du schéma, cette solution est maintenant implémentée dans le back, mais j'ai peur que ce ne soit pas très utile compte tenu du fait que notre première version de schéma (flyway baseline) soit la même que la dernière version de ce projet, mais ça nous a au moins permit de prendre en main l'outil et de comprendre à quoi il pourrait nous servir.

**Comment by arnaudperalta** [comment]
Il y a désormais un script d'initialisation (V1) et un autre qui intègre un jeu de données (v1.1)
