### ISSUE TITLE
[High] Profil

### ISSUE THREAD

**Issue by Nemtecl** [Open-Street-Art/osa-back#41]
Créer différents profil de développement (local, dev, recette par exemple) pour avoir différents mot de passes, chaine de connexion, secret pour le JWT....

Une explication/présentation pourra se faire en démonstration

**Comment by Abdellux** [comment]
8fd897e92839677212d9c8aa373ff2455dea75f2
création des profiles dev et recette

**Comment by arnaudperalta** [comment]
Les modifications apportées vous conviennent-elles ?

**Comment by Nemtecl** [comment]
Oui
