### ISSUE TITLE
[High] Normes RESTful

### ISSUE THREAD

**Issue by Nemtecl** [Open-Street-Art/osa-back#42]
Il faut passer l'ensemble des endpoints au pluriels (cities, arts...)
De plus on accède normalement a une oeuvre d'une ville via `/cities/:cityId/arts` et non pas via `/cities/arts/:cityId`
De même, pour accéder au contribs d'un utilisateur on passe par `/users/:userId/contribs`

**Comment by Abdellux** [comment]
d6c232f6cea8528c7918ebd791ddb577efec419a, c33fc04ff9210591b2513a7f2ec0a05351d821ed, ecb554f7ba00c7ebdf5a73e1865f9c91466a43b8, 792cf7e3855aa465da7dbccb41d4772ea25c3182
d6c232f6cea8528c7918ebd791ddb577efec419a, ecb554f7ba00c7ebdf5a73e1865f9c91466a43b8
eb0e38ba6a11d2bb1d4c5341fa974393a3ab0a62, 18d6668a6026b1fc5b3e52d7982e549c6725160a
ce sont les différents commits réalisés sur develop pour corriger les défauts liés à l'architecture SOA et la Norme Restful.
[High] Normes RESTful #42
[High]: Architecture SOA non respecté #44

**Comment by arnaudperalta** [comment]
Les modifications apportées vous conviennent-elles ?
