### ISSUE TITLE
[Normal]: Refacto du code

### ISSUE THREAD

**Issue by Nemtecl** [Open-Street-Art/osa-back#43]
Pour les `Optional<T>` il est existe une meilleure façon que la condition 

```java
if (!optional.isPresent())
```

On peut tout simplement faire

```java
if (optional.isEmpty())
```

De même, pour les listes 

```java
Collection<UserEntity> favArtists = new ArrayList<>();
for (UserEntity artist : user.getFavArtists()) {
	favArtists.add(artist);
}
```

Peut être fait en 

```java
Collection<UserEntity> favArtists = new ArrayList<>(user.getFavArtists());
```

Enfin les propriétés de ce type : 

```java
private static String contribNotFoundMsg = "Contribution not found.";
```

devrait être final

```java
private static final String contribNotFoundMsg = "Contribution not found.";
```

**Comment by arnaudperalta** [comment]
Les modifications ont été apportées dans ce commit : https://github.com/Open-Street-Art/osa-back/commit/678dc6933ae80c9d085ad5f9cbfaa2b7188702bf.

Je me suis permis de ne pas mettre ca dans une branche a part car l'issue ne concerne pas réellement d'amélioration de fonctionnalités de l'application.
