### ISSUE TITLE
[High]: Architecture SOA non respecté

### ISSUE THREAD

**Issue by Nemtecl** [Open-Street-Art/osa-back#44]
Dans une architecture SOA, le controleur utilise le service qui utilise les repositories.

Le code "métier" présent dans vos controleurs (qui utilise donc les Repo) devrait normalement être déplacé dans un service dédié.

Il est normal qu'un service pour les favoris par exemple utilise le userRepo, le favouriteRepo etc... Ce code est donc à migrer dans la couche service. 

En clair, le contrôleur devrait simplement avoir à faire un simple `myService.myMethod(myParams)`

**Comment by arnaudperalta** [comment]
Le code métier a été placé dans les différents service, cela vous convient-il ?
