### ISSUE TITLE
[Normal]: Définition inutiles de méthodes dans les repositories

### ISSUE THREAD

**Issue by Nemtecl** [Open-Street-Art/osa-back#45]
Les méthodes findById définies dans les repositories sont inutiles car elles sont déjà définies dans le CrudRepository que vous étendez.

**Comment by Khady-B** [comment]
Les méthodes findById définies dans les repositories ont été suprimées.
Vous pouvez le voir dans le commit : https://github.com/Open-Street-Art/osa-back/commit/80979b6928f452058e492dad3652075280373bec
