### ISSUE TITLE
[Low]: Utilisation d'annotation pour les rôles

### ISSUE THREAD

**Issue by Nemtecl** [Open-Street-Art/osa-back#46]
Il pourrait être interessant d'utiliser des annotations pour vérifier le rôle avant même d'entrer dans un endpoint (par exemple pour la partie Admin).

Cela permettrait de gagner en lisibilité et surtout d'éviter beaucoup de lignes de codes !

Voici un exemple d'utilisation : 

![image](https://user-images.githubusercontent.com/24937220/115436170-fcd32200-a20a-11eb-96e3-719e36d337ca.png)

**Comment by arnaudperalta** [comment]
Modifié directement sur la branche develop https://github.com/Open-Street-Art/osa-back/commit/b95dcb33911ed470470cc0879a4f10bc6f09eb9f . Merci pour le conseil !
